sources:
  - name: facebook
    database: bronze_production
    description: data from  facebook plaform (static)
    schema: cdc_staging
    config:
      enabled: true
      meta:
        owner: "@cde_engineer"
      freshness:
        warn_after:
          count: 2
          period: day

    tables:
      - name: campaign
        description: campaign data from  facebook plaform (static)
        config:
          enabled: true
          event_time: campaign_updated_at

      - name: adsgroup
        description: adgroups data from  facebook plaform (static)
        config:
          enabled: true
          event_time: ad_group_updated_at

      - name: ads
        description: ads data from  facebook plaform (static)
        config:
          enabled: true
          event_time: ad_updated_at

      - name: account
        description: accounts data from  facebook plaform (static)
        config:
          enabled: true
          event_time: account_updated_at